### ISSUE TITLE
Zero Pk with Zero Signature

### ISSUE THREAD

**Issue by davxy** [ZcashFoundation/ed25519-zebra#64]
Any comment about this feature?

```
let pk = VerificationKey::try_from([0; 32]).unwrap();
let sig = Signature::try_from([0; 64]).unwrap();
let msg = b"WHATEVER";
assert!(pk.verify(&sig, msg).is_ok());
```

Isn't this a potential "trap" for the user that naively registers *somewhere* a zero pk (where an implementor allows it) under its name opening the doors for easy impersonation?

I know I can have the same end result by publishing my private key in the wild. But the mechanics here are a bit different. Here the signature verifies every message, there isn't any relationship between the message and the signature.

**Comment by conradoplg** [comment]
That is a know "feature" of Ed25519, see [this discussion](https://github.com/jedisct1/libsodium/issues/112), and also the [security considerations of ZIP-215](https://zips.z.cash/zip-0215#security-and-privacy-considerations).

Unfortunately we can't change the behaviour because the signature is consensus-critical in Zcash (if we reject those signatures or keys we could cause a fork in the blockchain).
